language: java
notifications:
  email: false
  slack:
    secure: He3fYpkBRaXsWG+bFgEYnHTn1wcuGE1PIknKnayUmlw/wi5zeM/Kt78f7ZMxzRfyeh+7YSYkRz1qbnb9SBgKqk++x+7mjlQ0RuYs/ocNUkBJw0+672ztjFMcTakZNBSWd3CJq3x2VJVStE6IFc8UxyN063E29yuOsUjVD3XYoYDjAQqb6GpndYXPVLG7gBWFnbRGKaA9xzFML+HYaFc9MHEnlX8uJV6xq06YbX5iLzCOyUqhLUqRwuFbCmnT2qkXllTJYw6OaVMj3ZbPGit9MZgHy0idRCvuYsddmiQvwIBZ6940sJgZxwX79Jr8oh35yHSAZXGZ9Z0MRztBxyMgtN+pM/MoNL5QrGsR7ncqKHp4bndhk/Wrzas2a8kMWrJ77wxAUouxiHCMomH1sekQwQa6RWzViJxsCP9MCjiclOhhgiQpj785j3M0GBOGVLhXLyE8XyJFifvjNnCGlUKdCsPfXtpPSi2vuGr8SmkztcO2JKPEweFGzegjVY5L84JivFPWgq0XTvVzK1SOfhu5NRigzfCOaKcRkfvf1X7QqIN8tMmQzsdCNi8TIBrpMk1M81lQnDpwgaQYIzUcjQLJ/LglDw8LKaGqpEzO91eife1yj7VRvNPKOzwv5h5+QrgHXkOLAxjGzyAHYf6GEUgG1+H94hoq7BKlRJ9zDXol6x4=
jdk:
- oraclejdk8
install: echo 'Run Maven Tests'
script: mvn clean install --settings .travis/settings.xml -Dmaven.javadoc.skip=true -B -V
after_success: mvn deploy --settings .travis/settings.xml -DskipTests -B -V
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: SjQ+kCWuCyyLTDH4Az6f5x28nRz+x0TKP9s0F12rryr/MUAjnfNyWv/UiEKgQli+rcY5VI1kr/o1zJa3LTPQvsozeewvuaQ7oSs+HyyYW9E8auoVLZPy1MY0dL7bKZIAaZkSf6QAsfdBswYu/HmJHKkKKdidfA+rQFHG35Vd5Ermdil1d+xUZ/Eqg7UtRdMqOqV+mvZcgkY/jAsSuaTzNunHo5EwmUesUGbo63EZIgiiNhWY+q7rLdo3Gz2OkNxE3TjtKygDuZU29tur8YV2Kpv3I/OAodqC4aT++wHBvZNTgfgkIVdlCf6X8+8f3z3+TQzCVamF8sGpOlzNs81PcYQRaHUYbOUF9AD76HoVgH+sG7/LeSIyMl4HEJoKdQIcZUoJyOkrGZNtkilaLSTBic6NPMDx1MM1htjxIMTqY+2AVPQL9FQNAFhRhcN/5XmiFxrdKX3WCZUtStFjOHUaprHJsx3rNQ1GjHo4nFW0Bx6bHCxb1KdM5Jn6cIeTP1+Hgz5Xjrd8dMvNVhWtnB9jPBlhq0MaXpPicUBJVetgnhyzKnHJmTNylwlqJBrx+hDqA0ve0Ler9vxnGFs77WIye/eA8dSbbExQXjl+G3AVvW4U/uj7KkiDvao9h26N12A4Ru2I8yHZVx44iXEBg9IzlIlKS4AtXd+7dcfRytLcua0=
  - secure: vOpPNRyGW2RDgE0cuIenidRuTW0p1LS/EfCdXfS6af/G0f4AKzzlMP2aSrLbV6TsitdZ09TF4E2nK2sBiOXtm5umSei3VpG8OpSVQe6sdDgbMODTU8AOlZziuweRNEySFxRC6zk3rcK16j0Pek3LpgvcHByF9MWntV9z3tgYXRcnOFSaLIt4bnVzzam+DDZa0bWP1DMxsU0GgPT/f0wSDefsgsc5x0G9uECx9E6v8QZKbboZdJopC/gxyy1GIpKdVSNYOHnP7EZyxFOqAnPAyIsuFNZnF9cERs46acWmjAc4MwfwLiIuVhXSXm6orIgiudOsx6/vXQjEaaGzuN+ccRcolnEAniF5d3HEsesAGHNiR2W89eXgKgZ/FiCv+/Ecb7vOgxtlsLWvBhSjHLmBil43AHEJvBH1pmUbY6Jfes8aPx86XsQvzPwjxaOQUM1/VqDcasGmtRuA3eXkqwGO/9chMkI/Bdf6wFgTIcuE0nYYecRxYqwY35Pf1vXCFecO1uStR1zc5MxMbl2+hsbPgaOEabWFQvOd9Hwu4UofOH84YXlB8n1fTPzUzM6ndQP8pQEQaf0XLK1EqcHdDMxJ21vrTqXgKC2+OgNw9hTUwILLa1Pgx4NVShm1g3aRxJGUc/FtbjEMTNDcHgyWAw2BR12Lg9rMRuUTsJsxFCTo7uE=
